name: staff_app
description: Virtual Waiter - Staff App (MVP)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  http: ^1.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/beep.wav
